### ISSUE TITLE
Button mergin not correct

### ISSUE THREAD

**Issue by MoonieBoo** [jimmyeao/Elite-Dangerous-Add-On-Helper#19]
Hey jimmyeao,

Thank you for this Tool.

After I downloaded, install and start the program a few minutes ago, my Window looks like this:

![Screenshot_20221202_132000](https://user-images.githubusercontent.com/117904065/205292475-7b0ce0c0-2160-44f6-a918-4e92fdaf3afd.png)

Best regards

**Comment by jimmyeao** [comment]
Hey, thanks for the feedback! The code auto creates the controls, I suspect there is a problem with screen resolution - what screen resolution do you run, and do you have display scale set in display settings 👍🏻 
![image](https://user-images.githubusercontent.com/5197831/205317717-4f36ef41-efb6-4f43-bf11-f8eaa32c8084.png)

**Comment by MoonieBoo** [comment]
Hey ho,

I have the display resolution 1920px1080p with a scale of 100% - i will check the new release later and will let you know

**Comment by jimmyeao** [comment]
fixed in #25
