### ISSUE TITLE
REQ - Launch order - more options

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [jimmyeao/Elite-Dangerous-Add-On-Helper#24]
Hi, love the app....better than my 20 odd batch scripts I have, so thank you

Wondering if you can "float" the added apps so you can drag and drop the ordering...also add more than just VR/non VR

Ie trading/combat/engineers...as a seperate option

If Im in a session to run combat, I dont want some of the apps loaded
I also play both vr and non, so I might be doing a combat session in vr, then switch all the apps for engineering in non vr

**Comment by jimmyeao** [comment]
Hi, thanks for the feedback, its really appreciated.
We are working on a V2 app that will give you multiple profiles as you describe, and I'll investigate how easy it is to change the ordering :)

**Comment by jimmyeao** [comment]
Profiles have now been added to the latest release :)

**Comment by fusionmc-evilscoop** [comment]
you sir are a star...i will be trying that feature out a lot over the coming week :D
