### ISSUE TITLE
Question/Issue

### ISSUE THREAD

**Issue by WolfEagle1** [jimmyeao/Elite-Dangerous-Add-On-Helper#32]
Hi,

Nice app, very handy for ED given all the 3rd party tools.  Did you post this on the Frontier forums yet for more visibility?
I run ED through Steam and if I link your app directly to the ED .exe it requires me to log in through Frontier, vs the Steam icon/shortcut which bypasses that. Any ideas how to get this to launch without sign in?

**Comment by jimmyeao** [comment]
Did you get this working? If you are still having problems, send me your config over and Ill take a deeper look

**Comment by WolfEagle1** [comment]
I did, I had to create a custom shortcut and used the arguments field in your settings. see attached. Thanks for checking.  Everything works great.


    On Friday, March 3, 2023 at 04:59:44 AM CST, Jimmy White ***@***.***> wrote:  
 
 


Did you get this working? If you are still having problems, send me your config over and Ill take a deeper look

**Comment by jimmyeao** [comment]
Glad you got it working :)
